from __future__ import annotations

import json

from .planner import AIProvider


class MockProvider(AIProvider):
    """
    Fake AI provider used for testing the Developer pipeline.
    """

    def generate(
        self,
        prompt: str,
        temperature: float = 0.2,
    ) -> str:

        response = {
            "plugin_name": "HelloWorld",
            "plugin_type": "command",
            "description": "Simple Hello World plugin",
            "commands": ["hello"],
            "permissions": [],
            "requirements": [],
            "assumptions": [],
            "notes": ["Generated by MockProvider"],
            "confidence": 1.0,
        }

        return json.dumps(response)